Cadastro/Models/DbCadastro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cadastro.Models
{
    [Table("cadastro", Schema = "public")]
    public class DbCadastro
    {
        [Key]
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string rua { get; set; }
        public int numero { get; set; }
        public string cep { get; set; } 
        public string cidade { get; set; }
        public  string estado { get; set; }
    }
}

Cadastro/Models/DbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Cadastro.Models
{
    public class Context : DbContext
    {
        public Context(DbContextOptions<Context> opcoes) : base(opcoes) { }

        public DbSet<DbCadastro> Cadastros { get; set; }

    }
}

Cadastro/Models/ErrorViewModel.cs
namespace Cadastro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cadastro/Controllers/CadastroController.cs
using Cadastro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cadastro.Controllers
{
    public class CadastroController : Controller
    {
        private readonly Context _context;

        public CadastroController(Context context)
        {
            _context = context;
        }

        // GET: Cadastros
        public async Task<IActionResult> Index()
        {
            ViewBag.Nome = (from c in _context.Cadastros
                            select c.nome).Distinct();

            ViewBag.Email = (from c in _context.Cadastros
                             select c.email).Distinct();
            return View(await _context.Cadastros.ToListAsync());
        }

        // GET: Cadastros/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cadastros == null)
            {
                return NotFound();
            }

            var dbCadastro = await _context.Cadastros
                .FirstOrDefaultAsync(m => m.id == id);
            if (dbCadastro == null)
            {
                return NotFound();
            }

            return View(dbCadastro);
        }

        // GET: Cadastros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nome,email,rua,numero,cep,cidade,estado")] DbCadastro dbCadastro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dbCadastro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dbCadastro);
        }

        // GET: Cadastros/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cadastros == null)
            {
                return NotFound();
            }

            var dbCadastro = await _context.Cadastros.FindAsync(id);
            if (dbCadastro == null)
            {
                return NotFound();
            }
            return View(dbCadastro);
        }

        // POST: Cadastros/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome,email,rua,numero,cep,cidade,estado")] DbCadastro dbCadastro)
        {
            if (id != dbCadastro.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dbCadastro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DbCadastroExists(dbCadastro.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dbCadastro);
        }

        // GET: Cadastros/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cadastros == null)
            {
                return NotFound();
            }

            var dbCadastro = await _context.Cadastros
                .FirstOrDefaultAsync(m => m.id == id);
            if (dbCadastro == null)
            {
                return NotFound();
            }

            return View(dbCadastro);
        }

        // POST: Cadastros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cadastros == null)
            {
                return Problem("Entity set 'Context.Cadastros'  is null.");
            }
            var dbCadastro = await _context.Cadastros.FindAsync(id);
            if (dbCadastro != null)
            {
                _context.Cadastros.Remove(dbCadastro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DbCadastroExists(int id)
        {
            return (_context.Cadastros?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Cadastro/Controllers/HomeController.cs
using Cadastro.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cadastro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cadastro/Views/Cadastro/Create.cshtml
@model Cadastro.Models.DbCadastro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rua" class="control-label"></label>
                <input asp-for="rua" class="form-control" />
                <span asp-validation-for="rua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numero" class="control-label"></label>
                <input asp-for="numero" class="form-control" />
                <span asp-validation-for="numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cep" class="control-label"></label>
                <input asp-for="cep" class="form-control" />
                <span asp-validation-for="cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cidade" class="control-label"></label>
                <input asp-for="cidade" class="form-control" />
                <span asp-validation-for="cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estado" class="control-label"></label>
                <input asp-for="estado" class="form-control" />
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cadastro/Views/Cadastro/Delete.cshtml
@model Cadastro.Models.DbCadastro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a> |
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        
    </form>
</div>

Cadastro/Views/Cadastro/Details.cshtml
@model Cadastro.Models.DbCadastro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a> |
    <a asp-action="Edit" asp-route-id="@Model?.id"><i class="fa-solid fa-pen-to-square"></i></a>
</div>

Cadastro/Views/Cadastro/Edit.cshtml
@model Cadastro.Models.DbCadastro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rua" class="control-label"></label>
                <input asp-for="rua" class="form-control" />
                <span asp-validation-for="rua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numero" class="control-label"></label>
                <input asp-for="numero" class="form-control" />
                <span asp-validation-for="numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cep" class="control-label"></label>
                <input asp-for="cep" class="form-control" />
                <span asp-validation-for="cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cidade" class="control-label"></label>
                <input asp-for="cidade" class="form-control" />
                <span asp-validation-for="cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estado" class="control-label"></label>
                <input asp-for="estado" class="form-control" />
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                 <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a> |
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cadastro/Views/Cadastro/Index.cshtml
@model IEnumerable<Cadastro.Models.DbCadastro>

@{
    ViewData["Title"] = "Index";
}

<h1>Formulario de Cadastro</h1>


<p>
    <a asp-action="Create"><i class="fa-solid fa-plus"></i></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                Email
            </th>
            <th>
                Rua
            </th>
            <th>
                Numero
            </th>
            <th>
                CEP
            </th>
            <th>
                Cidade
            </th>
            <th>
                Estado
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.rua)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cep)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id"><i class="fa-solid fa-pen-to-square"></i></a> | 
                    <a asp-action="Details" asp-route-id="@item.id"><i class="fa-solid fa-list"></i></a> | 
                    <a asp-action="Delete" asp-route-id="@item.id"><i class="fa-solid fa-trash"></i></a>                   

                </td>
            </tr>
        }
    </tbody>
</table>

Cadastro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Cadastro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cadastro.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-6.1.1-web/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trabalho de Programação Visual</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastro" asp-action="Index">Cadastrar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Trabalho de Programação Visual - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>